const test = {
  title:
    "Olympia Tools 48-Inch Hardwood Workbench 330lbs Weight Capacity, 88-128-917 Acacia Wood (88-128-917) Workbench",
  search_alias: { title: "Tools & Home Improvement", value: "tools" },
  title_excluding_variant_name:
    "Olympia Tools 48-Inch Hardwood Workbench 330lbs Weight Capacity, 88-128-917",
  keywords:
    "Olympia,Tools,48-Inch,Hardwood,Workbench,330lbs,Weight,Capacity,,88-128-917",
  keywords_list: [
    "Olympia",
    "Tools",
    "48-Inch",
    "Hardwood",
    "Workbench",
    "330lbs",
    "Weight",
    "Capacity",
    "88-128-917",
  ],
  asin: "B087D88ZJM",
  parent_asin: "B089XDFNW5",
  link: "https://www.amazon.com/Olympia-Tools-Hardwood-Workbench-88-128-917/dp/B087D88ZJM",
  brand: "Olympia Tools",
  sell_on_amazon: true,
  variants: [
    {
      asin: "B087D88ZJM",
      title: "Acacia Wood (88-128-917) Workbench",
      is_current_product: true,
      link: "https://www.amazon.com/dp/B087D88ZJM?th=1&psc=1",
      dimensions: [Array],
      main_image:
        "https://m.media-amazon.com/images/I/71s3tkMQReL._AC_SL1500_.jpg",
      images: [Array],
    },
    {
      asin: "B071RH3VW7",
      title: "Rubber Wood (84-906) Workbench",
      is_current_product: false,
      link: "https://www.amazon.com/dp/B071RH3VW7?th=1&psc=1",
      dimensions: [Array],
      main_image:
        "https://m.media-amazon.com/images/I/814l4dA-5sL._AC_SL1500_.jpg",
      images: [Array],
    },
    {
      asin: "B0BMKQG8LF",
      title: "4-Drawer Rubberwood (90-561) 4-Drawer Rubberwood (90-561)",
      is_current_product: false,
      link: "https://www.amazon.com/dp/B0BMKQG8LF?th=1&psc=1",
      dimensions: [Array],
      main_image:
        "https://m.media-amazon.com/images/I/71fzt2rShhL._AC_SL1500_.jpg",
      images: [Array],
    },
  ],
  variant_asins_flat: "B087D88ZJM,B071RH3VW7,B0BMKQG8LF",
  categories: [
    {
      name: "Tools & Home Improvement",
      link: "https://www.amazon.com/Tools-and-Home-Improvement/b/ref=dp_bc_aui_C_1?ie=UTF8&node=228013",
      category_id: "228013",
    },
    {
      name: "Building Supplies",
      link: "https://www.amazon.com/Building-Supply-and-Building-Materials/b/ref=dp_bc_aui_C_2?ie=UTF8&node=551240",
      category_id: "551240",
    },
    {
      name: "Material Handling",
      link: "https://www.amazon.com/material-handling/b/ref=dp_bc_aui_C_3?ie=UTF8&node=553516",
      category_id: "553516",
    },
    {
      name: "Workbenches",
      link: "https://www.amazon.com/workbench/b/ref=dp_bc_aui_C_4?ie=UTF8&node=553602",
      category_id: "553602",
    },
  ],
  categories_flat:
    "Tools & Home Improvement > Building Supplies > Material Handling > Workbenches",
  a_plus_content: {
    has_a_plus_content: true,
    has_brand_story: false,
    third_party: false,
  },
  sub_title: {
    text: "Visit the Olympia Tools Store",
    link: "https://www.amazon.com/stores/OlympiaTools/page/B8968B9C-0D73-4CBB-9092-DD67A06C9362?ref_=ast_bln",
  },
  rating: 4.2,
  rating_breakdown: {
    five_star: { percentage: 59, count: 526 },
    four_star: { percentage: 20, count: 178 },
    three_star: { percentage: 11, count: 98 },
    two_star: { percentage: 4, count: 35 },
    one_star: { percentage: 6, count: 53 },
  },
  ratings_total: 892,
  main_image: { link: "https://m.media-amazon.com/images/I/71s3tkMQReL.jpg" },
  images: [
    {
      link: "https://m.media-amazon.com/images/I/71s3tkMQReL._AC_SL1500_.jpg",
      variant: "MAIN",
    },
    {
      link: "https://m.media-amazon.com/images/I/81IPFk5+u7L._AC_SL1500_.jpg",
      variant: "PT01",
    },
    {
      link: "https://m.media-amazon.com/images/I/71-wmOTeQ4L._AC_SL1500_.jpg",
      variant: "PT02",
    },
    {
      link: "https://m.media-amazon.com/images/I/81ahFHKzJ6L._AC_SL1500_.jpg",
      variant: "PT03",
    },
    {
      link: "https://m.media-amazon.com/images/I/81LT46-CdjL._AC_SL1500_.jpg",
      variant: "PT04",
    },
    {
      link: "https://m.media-amazon.com/images/I/81Ua+eTnXsL._AC_SL1500_.jpg",
      variant: "PT05",
    },
    {
      link: "https://m.media-amazon.com/images/I/919cv04iROL._AC_SL1500_.jpg",
      variant: "PT06",
    },
    {
      link: "https://m.media-amazon.com/images/I/81xRIXugieL._AC_SL1500_.jpg",
      variant: "PT07",
    },
    {
      link: "https://m.media-amazon.com/images/I/81oyLyRx1DL._AC_SL1500_.jpg",
      variant: "PT08",
    },
    {
      link: "https://m.media-amazon.com/images/I/71b4O2jJybL._AC_SL1500_.jpg",
      variant: "PT09",
    },
    {
      link: "https://m.media-amazon.com/images/I/71miO9U2dzL._AC_SL1500_.jpg",
      variant: "PT10",
    },
  ],
  images_count: 11,
  images_flat:
    "https://m.media-amazon.com/images/I/71s3tkMQReL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/81IPFk5+u7L._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/71-wmOTeQ4L._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/81ahFHKzJ6L._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/81LT46-CdjL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/81Ua+eTnXsL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/919cv04iROL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/81xRIXugieL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/81oyLyRx1DL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/71b4O2jJybL._AC_SL1500_.jpg,https://m.media-amazon.com/images/I/71miO9U2dzL._AC_SL1500_.jpg",
  videos: [
    {
      duration_seconds: 44,
      width: 854,
      height: 480,
      link: "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/58de8b56-9fe8-4ea0-b524-067ac391f32f/default.jobtemplate.mp4.480.mp4",
      thumbnail: "https://m.media-amazon.com/images/I/C1JnpKaiZoS.SX522_.jpg",
      is_hero_video: false,
      variant: "MAIN",
      group_id: "IB_G1",
      group_type: "videos_for_this_product",
      title: "Product Introduction Video - Acacia Workbench",
    },
    {
      duration_seconds: 99,
      width: 854,
      height: 480,
      link: "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/37556da2-cbc1-4829-8778-56df421491ff/default.jobtemplate.mp4.480.mp4",
      thumbnail: "https://m.media-amazon.com/images/I/B1N54cHZttS.SX522_.jpg",
      is_hero_video: false,
      variant: "MAIN",
      group_id: "IB_G1",
      group_type: "videos_for_this_product",
      title: "Assembly Instruction Videos - Acacia workbenc",
    },
  ],
  videos_count: 2,
  videos_flat:
    "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/58de8b56-9fe8-4ea0-b524-067ac391f32f/default.jobtemplate.mp4.480.mp4,https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/37556da2-cbc1-4829-8778-56df421491ff/default.jobtemplate.mp4.480.mp4",
  videos_additional: [
    {
      id: "amzn1.vse.video.0b27a36741424372a88fda20c18f5bb2",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B087D88ZJM",
      sponsor_products: "true",
      title: "Wrong parts",
      profile_image_url:
        "https://www.amazon.com/avatar/default/amzn1.account.AHIXXYGY3PC4CZ2HN5I6XII7NKHQ?max_width=110&square=true",
      profile_link: "/gp/profile/amzn1.account.AHIXXYGY3PC4CZ2HN5I6XII7NKHQ",
      public_name: "eddie escalante",
      creator_type: "Customer",
      vendor_code: "UGCPR",
      vendor_name: "eddie escalante",
      video_image_id: "310ZbV1LJBL",
      video_image_url:
        "https://m.media-amazon.com/images/I/310ZbV1LJBL._CR0,0,360,203_SR342,193_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/310ZbV1LJBL.jpg",
      video_image_width: "360",
      video_image_height: "480",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/39b08f8a-6380-45a4-88cf-e718356c4eb2/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/6e5e216b-4fd5-45a0-be07-b8a0a014c845/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "0:16",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/277f4ff3-b140-42ed-84f6-947b432b0d67.vtt",
      type: "videos_for_this_product",
    },
    {
      id: "amzn1.vse.video.f0226c5fa387452f96616b5aa7514362",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B087D88ZJM",
      sponsor_products: "true",
      title: "Assembly Instruction Videos - Acacia workbenc",
      public_name: "Kunjek-VN",
      creator_type: "Seller",
      vendor_code: "Z7AX4",
      vendor_name: "Kunjek-VN",
      video_image_id: "B1N54cHZttS",
      video_image_url:
        "https://m.media-amazon.com/images/I/B1N54cHZttS._CR0,0,3756,2120_SR684,386_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/B1N54cHZttS.jpg",
      video_image_width: "3756",
      video_image_height: "3280",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/37556da2-cbc1-4829-8778-56df421491ff/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/fdef2ad9-b76a-4f84-beed-6e852526235a/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "1:39",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/6d4676a9-6e55-4a3b-b119-b13764f07f54.vtt",
      type: "videos_for_this_product",
    },
    {
      id: "amzn1.vse.video.7de18cffb65841f2bc7d0eee52a2fc81",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B087D88ZJM",
      sponsor_products: "true",
      title: "Product Introduction Video - Acacia Workbench",
      public_name: "Kunjek-VN",
      creator_type: "Seller",
      vendor_code: "Z7AX4",
      vendor_name: "Kunjek-VN",
      video_image_id: "C1JnpKaiZoS",
      video_image_url:
        "https://m.media-amazon.com/images/I/C1JnpKaiZoS._CR0,0,6048,3413_SR684,386_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/C1JnpKaiZoS.jpg",
      video_image_width: "6048",
      video_image_height: "4120",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/58de8b56-9fe8-4ea0-b524-067ac391f32f/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/ff6dbc58-7cf0-4c79-b267-3a177b8c746b/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "0:44",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/1e3b5264-7f80-43a9-930b-55e2672408b1.vtt",
      type: "videos_for_this_product",
    },
    {
      id: "amzn1.vse.video.18a79a884bc54a76a6e4642f4c7c3a7f",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B087D88ZJM",
      sponsor_products: "true",
      title: "48-Inch Hardwood Workbench 330lbs Weight Capacity, 88-128-917",
      public_name: "Olympia Tools International Inc",
      creator_type: "Vendor",
      vendor_code: "137GO",
      vendor_name: "Olympia Tools International Inc",
      video_image_id: "51zZkWH-duL",
      video_image_url:
        "https://m.media-amazon.com/images/I/51zZkWH-duL._CR0,0,640,361_SR342,193_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/51zZkWH-duL.jpg",
      video_image_width: "640",
      video_image_height: "640",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/5216ebe2-8369-4b39-987d-54f64e9d35f4/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/f96e0cfe-679b-4366-b7d3-2dc76c90305e/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "0:42",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/ec1a06f9-e384-4f55-bd17-1fea979fb069.vtt",
      type: "videos_for_this_product",
    },
    {
      id: "amzn1.vse.video.0f3a524254f847bdbe6c9d99506a7391",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B08BNZDB57, B08M3T1JN4",
      sponsor_products: "true",
      title: "WORKPRO Adjustable Workbench",
      public_name: "GreatStar Tools",
      creator_type: "Seller",
      vendor_code: "Z7AX4",
      vendor_name: "GreatStar Tools",
      video_image_id: "51vN7jOG6lL",
      video_image_url:
        "https://m.media-amazon.com/images/I/51vN7jOG6lL._CR1,0,638,360_SR342,193_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/51vN7jOG6lL.jpg",
      video_image_width: "640",
      video_image_height: "360",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/16ed9fb5-d613-4073-90be-c289a872b7af/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/60f24d1e-ce27-4755-855a-bdceaf6fe800/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "0:47",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/82a1e7c9-2257-4550-9773-baa91058796d.vtt",
      type: "videos_for_related_products",
    },
    {
      id: "amzn1.vse.video.016ef55466a44efe8808e3a10f4e59e7",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B09VXCW6VS, B09VXF3S81",
      sponsor_products: "true",
      title: '48" Heavy-Duty Adjustable Workbench for Garage',
      public_name: "TOLEAD Direct",
      creator_type: "Seller",
      vendor_code: "Z7AX4",
      vendor_name: "TOLEAD Direct",
      video_image_id: "81N3uQk55fL",
      video_image_url:
        "https://m.media-amazon.com/images/I/81N3uQk55fL._CR0,0,2000,1129_SR684,386_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/81N3uQk55fL.jpg",
      video_image_width: "2000",
      video_image_height: "2000",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/a1f7b303-5ec0-45db-a3ef-c193a59700be/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/be061701-c272-46df-99ef-6b8c9a3b08bd/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "0:27",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/08a3de19-87ee-4c32-8aaa-3096e8db3b30.vtt",
      type: "videos_for_related_products",
    },
    {
      id: "amzn1.vse.video.0050ccdeb076416da17a39f7f9751a67",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B0BFGTFB6J, B0BKFGV1B8",
      sponsor_products: "true",
      title: "Tool table installation details video",
      public_name: "JolinLife",
      creator_type: "Seller",
      vendor_code: "Z7AX4",
      vendor_name: "JolinLife",
      video_image_id: "41NrQFN8NRL",
      video_image_url:
        "https://m.media-amazon.com/images/I/41NrQFN8NRL._CR0,0,640,361_SR342,193_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/41NrQFN8NRL.jpg",
      video_image_width: "640",
      video_image_height: "368",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/0822915f-a09b-4e4c-966e-bd883516e3f3/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/e850dff5-8d10-4d79-b32f-5a6a33f7d061/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "0:45",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/6060cf95-e0c4-4988-94ee-fa91c3c67768.vtt",
      type: "videos_for_related_products",
    },
    {
      id: "amzn1.vse.video.060fa56801394e32b7de3741c69e3674",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B08ZW1KYZN, B094NB59W7",
      sponsor_products: "true",
      title: "Great Workbench Review ",
      profile_image_url:
        "https://images-na.ssl-images-amazon.com/images/S/influencer-profile-image-prod/logo/bullets4bucks_1627341576691_original._CR0,0,500,500_._FMjpg_.png",
      profile_link: "/shop/bullets4bucks",
      public_name: "Pure Wyoming Productions LLC",
      creator_type: "Influencer",
      vendor_code: "bullets4bucks:shop",
      vendor_name: "Pure Wyoming Productions LLC",
      vendor_tracking_id: "bullets4buc0b-20",
      video_image_id: "61HS6Oe5dsL",
      video_image_url:
        "https://m.media-amazon.com/images/I/61HS6Oe5dsL._CR1,0,638,360_SR342,193_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/61HS6Oe5dsL.jpg",
      video_image_width: "640",
      video_image_height: "360",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/b55fce87-1e27-4334-ba0d-dfd1b7491185/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/8d37aa4c-470d-441d-b080-2e8e62ba5fc9/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "2:14",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/18f2e730-20d0-4e80-b013-9cde3e1bfaf5.vtt",
      type: "videos_for_related_products",
    },
    {
      id: "amzn1.vse.video.0ca4ea5a7ab74f44ac43bb3db4ab71d8",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B07QG4FJSY, B07SDG6TY7",
      sponsor_products: "true",
      title: "Awesome butcher block work bench - easy to assemble ` ",
      profile_image_url:
        "https://images-na.ssl-images-amazon.com/images/S/influencer-profile-image-prod/stevesherron_1f4f3226-1ce6-47a1-a6b5-c81dae58c996.jpeg",
      profile_link: "/shop/stevesherron",
      public_name: "Steve Sherron",
      creator_type: "Influencer",
      vendor_code: "stevesherron:shop",
      vendor_name: "Steve Sherron",
      vendor_tracking_id: "adventureou03-20",
      video_image_id: "B1D5BKfnudS",
      video_image_url:
        "https://m.media-amazon.com/images/I/B1D5BKfnudS._CR3,0,1914,1080_SR684,386_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/B1D5BKfnudS.jpg",
      video_image_width: "1920",
      video_image_height: "1080",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/8c0d112c-68b6-4bcd-a50a-11265d7fbe80/default.jobtemplate.hls.m3u8",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/01de8b7e-1deb-40d7-af1b-1d0a1ec837a3/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "application/x-mpegURL",
      duration: "3:09",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/eb7dfc5e-4d5f-4384-9064-36ba567527ed.vtt",
      type: "videos_for_related_products",
    },
    {
      id: "amzn1.vse.video.b647e53fe5f84f87aae0b7d22a65012f",
      product_asin: "B087D88ZJM",
      parent_asin: "B089XDFNW5",
      related_products: "B071RH3VW7",
      sponsor_products: "true",
      title: "Olympia Tools 84-906 Hard Wood Workbench",
      public_name: "Merchant Video",
      vendor_code: "V3MSA",
      vendor_name: "Merchant Video",
      video_image_id: "61kbME9oL-L",
      video_image_url:
        "https://m.media-amazon.com/images/I/61kbME9oL-L._CR2,0,716,404_SR684,386_.jpg",
      video_image_url_unchanged:
        "https://m.media-amazon.com/images/I/61kbME9oL-L.jpg",
      video_image_width: "720",
      video_image_height: "404",
      video_image_extension: "jpg",
      video_url:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/cbac9c87-c07d-52fe-831e-eaa60fbfba13/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4",
      video_previews:
        "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/6ae5f78f-2d63-49f1-9169-01b391af02ec/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
      video_mime_type: "video/mp4",
      duration: "1:10",
      closed_captions:
        "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/2861cc62-33cd-4877-add1-d85a900fbe5b.vtt",
      type: "videos_for_related_products",
    },
  ],
  is_bundle: false,
  feature_bullets: [
    "Easy Woodworking: This multipurpose bench is ideal for your next carpentry or woodworking project. Measuring 4 feet in length and 1 feet 8 inch in depth, it is an ideal size for your garage or shop.",
    "Carpentry and Assembly: Crafted from hard Acacia wood with varnish finish, this bench features a slide drawer and convenient storage shelf. Ready for any home or professional workshop.",
    "Made to Last: Our durable and long-lasting tools help you with home, garage and industrial projects. With professional-grade quality, easily repair and fix issues with our tool cabinet essentials",
    "The Right Tool for the Job: We engineer a range of bolt cutters, clamps, chisels, folding carts, hammers, pliers, saws, screwdrivers, tape measures, utility knives, vises, bolt cutters, saws and wrenches",
    "Superior Instruments: Olympia Tools provides quality and innovative hand and specialty tools, tool accessories and outdoor equipment for construction, woodworking, mechanical maintenance and home repair",
  ],
  feature_bullets_count: 5,
  feature_bullets_flat:
    "Superior Instruments: Olympia Tools provides quality and innovative hand and specialty tools, tool accessories and outdoor equipment for construction, woodworking, mechanical maintenance and home repair. The Right Tool for the Job: We engineer a range of bolt cutters, clamps, chisels, folding carts, hammers, pliers, saws, screwdrivers, tape measures, utility knives, vises, bolt cutters, saws and wrenches. Made to Last: Our durable and long-lasting tools help you with home, garage and industrial projects. With professional-grade quality, easily repair and fix issues with our tool cabinet essentials. Carpentry and Assembly: Crafted from hard Acacia wood with varnish finish, this bench features a slide drawer and convenient storage shelf. Ready for any home or professional workshop. Easy Woodworking: This multipurpose bench is ideal for your next carpentry or woodworking project. Measuring 4 feet in length and 1 feet 8 inch in depth, it is an ideal size for your garage or shop.",
  attributes: [
    { name: "Material", value: "Wood" },
    { name: "Brand", value: "Olympia Tools" },
    {
      name: "Item Dimensions LxWxH",
      value: "55.51 x 20.87 x 5.12 inches",
    },
    { name: "Color", value: "Natural" },
    { name: "Item Weight", value: "0.01 Ounces" },
  ],
  top_reviews: [
    {
      id: "R3BJ0F2KIGSH85",
      title: "Acacia wood is beautiful, very hard however splinters easy.",
      body: "The table was built for beauty and fits that build the wood is what I bought it for, since then I have made changes that remove the parts trough and extend the bench with hard Maple. I have added an additional layer to the underside to strengthen the table, as well as adding white oak to two sides of the legs which make the weight limit almost triple that of the original spec. I bought the table for its looks; I beefed the strength to make it a practical heavy woodworking table. I recommend this table for its looks it will spruce up any workshop.Read more",
      body_html:
        '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>The table was built for beauty and fits that build the wood is what I bought it for, since then I have made changes that remove the parts trough and extend the bench with hard Maple. I have added an additional layer to the underside to strengthen the table, as well as adding white oak to two sides of the legs which make the weight limit almost triple that of the original spec. I bought the table for its looks; I beefed the strength to make it a practical heavy woodworking table. I recommend this table for its looks it will spruce up any workshop.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
      link: "https://www.amazon.com/gp/customer-reviews/R3BJ0F2KIGSH85/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 4,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "R1D03TP3PHBKWT",
      title: "Good value.  Sturdy little workbench.",
      body: "Some cosmetic blemishes, nothing big. Piece 13R had a broken dowel peg, I drilled it out and put my own dowel peg in. Did not come with wood screws but I used my own. So, some minor hiccups no fault of the seller, I’m sure these blemishes and mistakes happened in Vietnam where it was manufactured. All in all a good deal for the price.Read more",
      body_html:
        '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>Some cosmetic blemishes, nothing big. Piece 13R had a broken dowel peg, I drilled it out and put my own dowel peg in. Did not come with wood screws but I used my own. So, some minor hiccups no fault of the seller, I’m sure these blemishes and mistakes happened in Vietnam where it was manufactured. All in all a good deal for the price.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
      link: "https://www.amazon.com/gp/customer-reviews/R1D03TP3PHBKWT/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 4,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      images: [Array],
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "RYG3O6NIOHILV",
      title: "4 out of 5 because of…",
      body: "This is a great little work bench. The reason why I gave it 4 out of five stars is because the assembly instructions were not clear. But was able to figure it out. Out side of that I use it for leather work not woodworking and I may just end up filling the preexisting holes in the table since they serve zero purpose for me.Read more",
      body_html:
        '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>This is a great little work bench. The reason why I gave it 4 out of five stars is because the assembly instructions were not clear. But was able to figure it out. Out side of that I use it for leather work not woodworking and I may just end up filling the preexisting holes in the table since they serve zero purpose for me.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
      link: "https://www.amazon.com/gp/customer-reviews/RYG3O6NIOHILV/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 4,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "R2W4ZB2E5IEKS0",
      title: "What I Expected",
      body: "Just what you might expect for a very cheap woodworking table. I would not recommend this as your primary hand-tool woodworking bench but it should be exactly what I need for a mobile parts/assembly/outfeed table with a few modifications.  Pro's - Hardwood - Looks a nicer than most plywood and 2x4 benches - Costs less than what you could build it for with current wood prices - Includes bench dogs and pre-dilled holes - Has a drawer and a shelf  Con's - Joinery is not stiff and the table racks very easily - Lightweight so it moves too easily - Instructions are typical of this type of furniture - steps are missing and photos can be unclear (if you're a woodworker or any type of crafter or DIY'er, you should be fine though) - The vise is crooked due to the support bars being installed at angle. Probably not an issue so I'm not going to make a new end piece for now. - Will require braces which will limit access to the bottom shelf on three sides.  Upgrades - I plan to install support braces on the back and sides that should eliminate any racking. Then I will add leveling feet to handle my uneven floor and finally some retractable casters.Read more",
      body_html: `<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>Just what you might expect for a very cheap woodworking table. I would not recommend this as your primary hand-tool woodworking bench but it should be exactly what I need for a mobile parts/assembly/outfeed table with a few modifications.<br><br>Pro's<br>- Hardwood<br>- Looks a nicer than most plywood and 2x4 benches<br>- Costs less than what you could build it for with current wood prices<br>- Includes bench dogs and pre-dilled holes<br>- Has a drawer and a shelf<br><br>Con's<br>- Joinery is not stiff and the table racks very easily<br>- Lightweight so it moves too easily<br>- Instructions are typical of this type of furniture - steps are missing and photos can be unclear (if you're a woodworker or any type of crafter or DIY'er, you should be fine though)<br>- The vise is crooked due to the support bars being installed at angle. Probably not an issue so I'm not going to make a new end piece for now.<br>- Will require braces which will limit access to the bottom shelf on three sides.<br><br>Upgrades - I plan to install support braces on the back and sides that should eliminate any racking. Then I will add leveling feet to handle my uneven floor and finally some retractable casters.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>`,
      link: "https://www.amazon.com/gp/customer-reviews/R2W4ZB2E5IEKS0/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 4,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      helpful_votes: 11,
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "R1TP7TN50ZP4GX",
      title: "Missing parts otherwise Good",
      body: "Table Wood is solid, dense, with a nice finish.  MISSING the four wooden pegs (10), not packed.  I'd rate Craftsmanship high but for one significant oversight. The wood-vise can be mounted on the end of the table to allow use with long work pieces. But missing drilled holes for table wood-vice component remounting. I will drill copy holes from the side mounting patterned and remounting the vice table hardware (should come unmounted for user selection).  I will be adding lockable casters to the legs for easier shop movement/storage.Read more",
      body_html: `<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>Table Wood is solid, dense, with a nice finish.<br><br>MISSING the four wooden pegs (10), not packed.<br><br>I'd rate Craftsmanship high but for one significant oversight.<br>The wood-vise can be mounted on the end of the table to allow use with long work pieces. But missing drilled holes for table wood-vice component remounting. I will drill copy holes from the side mounting patterned and remounting the vice table hardware (should come unmounted for user selection).<br><br>I will be adding lockable casters to the legs for easier shop movement/storage.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>`,
      link: "https://www.amazon.com/gp/customer-reviews/R1TP7TN50ZP4GX/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 3,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "R16CGC5PULXGP6",
      title: "Difficult directions",
      body: "The product is beautiful and looks very durable, my only issue is the directions were very poorly written and so small I needed my reading glasses, did not make it easy while trying to assemble something and read tiny directions. Overall I am satisfied with the purchase, but whoever designs the put together of these items needs to rethink how they label pieces and how the furniture should be organized as you put it together, it was ridiculous putting together the drawer before I put together the top, the drawer would have been much easier to assemble once the top was affixed and I could have looked at how the pieces fit together, a very frustrating 2 1/2 hours. Pro tip, use wood glue on every piece, I went through a whole bottle, and this thing is never ever gonna come apart.Read more",
      body_html:
        '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>The product is beautiful and looks very durable, my only issue is the directions were very poorly written and so small I needed my reading glasses, did not make it easy while trying to assemble something and read tiny directions. Overall I am satisfied with the purchase, but whoever designs the put together of these items needs to rethink how they label pieces and how the furniture should be organized as you put it together, it was ridiculous putting together the drawer before I put together the top, the drawer would have been much easier to assemble once the top was affixed and I could have looked at how the pieces fit together, a very frustrating 2 1/2 hours. Pro tip, use wood glue on every piece, I went through a whole bottle, and this thing is never ever gonna come apart.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
      link: "https://www.amazon.com/gp/customer-reviews/R16CGC5PULXGP6/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 4,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "R2W439Y0S1QITT",
      title: "Quality desk, TERRIBLE instructions",
      body: "Let me start by saying that this is a solid wood table and I love it for that reason. I needed a workbench to make jewelry at home since it’s hard to get into my workshop that I rent due to Covid-19 whereas that the maximum capacity for places are very low now. So working from home is my solution. I gave it 4 stars because the instructions were absolutely terrible. So bad that I would have just been better looking at the pics on here and figuring out on my own how to assemble it. A few things: 1- when putting on the wooden brackets where the drawer slides it doesn’t tell which screws to use so I had to look ahead and set aside the screws ahead and deduct from that to figure out which ones i needed to use. 2- the pictures are in black and white with a terrible resolution so it’s just not clear enough to really look at and guess what to do so those sliding brackets too me a while to figure out the correct position to place them. 3- the numbers labeled on the drawers were inverted (15 and 16) so I had to figure that out. 4- the predrilled holes were only marked on one side when its time to attach the legs so if you’re trying to line the holes up on one side that’s not marked you’ll think you’re supposed to screw them into the bigger holes. The instruction manual had no verbiage about which holes to line up and screw into. When I state these things, I say this as a person who puts together furniture all the time from places like IKEA which baffles a lot of people but not me. Plus I’m a jeweler so I’m used to figuring out how to put things together in that aspect too. I don’t normally right reviews at all especially negative ones but those instructions were just that bad. Because it’s solid wood and very good quality, i would give that 5 stars but the putting together part deserves a flat out zero.Read more",
      body_html:
        '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>Let me start by saying that this is a solid wood table and I love it for that reason. I needed a workbench to make jewelry at home since it’s hard to get into my workshop that I rent due to Covid-19 whereas that the maximum capacity for places are very low now. So working from home is my solution. I gave it 4 stars because the instructions were absolutely terrible. So bad that I would have just been better looking at the pics on here and figuring out on my own how to assemble it. A few things: 1- when putting on the wooden brackets where the drawer slides it doesn’t tell which screws to use so I had to look ahead and set aside the screws ahead and deduct from that to figure out which ones i needed to use. 2- the pictures are in black and white with a terrible resolution so it’s just not clear enough to really look at and guess what to do so those sliding brackets too me a while to figure out the correct position to place them. 3- the numbers labeled on the drawers were inverted (15 and 16) so I had to figure that out. 4- the predrilled holes were only marked on one side when its time to attach the legs so if you’re trying to line the holes up on one side that’s not marked you’ll think you’re supposed to screw them into the bigger holes. The instruction manual had no verbiage about which holes to line up and screw into. When I state these things, I say this as a person who puts together furniture all the time from places like IKEA which baffles a lot of people but not me. Plus I’m a jeweler so I’m used to figuring out how to put things together in that aspect too. I don’t normally right reviews at all especially negative ones but those instructions were just that bad. Because it’s solid wood and very good quality, i would give that 5 stars but the putting together part deserves a flat out zero.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
      link: "https://www.amazon.com/gp/customer-reviews/R2W439Y0S1QITT/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B087D88ZJM",
      rating: 4,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      images: [Array],
      helpful_votes: 7,
      review_country: "us",
      is_global_review: false,
    },
    {
      id: "R3877VDRAO5RPI",
      title:
        "Warped plywood. Finger joints. Poor instructions. BUT WAIT, THERE'S MORE...",
      body: "The bench was 19 inches deep, not 24. Metal hardware was all loose in the box. Wood was of poor quality, it was not hard rubber wood, as ad states. I was looking forward to a bench made of hard rubber wood. It was not lacquer coated. Plywood parts were warped. No felt-lined drawer. It looked like the bench was a return. And the wood block vise with adjustable machined guides had no adjustable guides. Protective plastic was a mess. And the Instruction Manual... whew. I'm a retired technical writer. If I had done that manual and handed it in for approval. Whew. Our director would have walked into my office, plopped it down on my desk saying, REALLY? Turned and walked out... and shut the lights off as he left. Whew. Pathetic. What I really loved about the bench was returning it. They paid for the return.Read more",
      body_html: `<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>The bench was 19 inches deep, not 24. Metal hardware was all loose in the box. Wood was of poor quality, it was not hard rubber wood, as ad states. I was looking forward to a bench made of hard rubber wood. It was not lacquer coated. Plywood parts were warped. No felt-lined drawer. It looked like the bench was a return. And the wood block vise with adjustable machined guides had no adjustable guides. Protective plastic was a mess. And the Instruction Manual... whew. I'm a retired technical writer. If I had done that manual and handed it in for approval. Whew. Our director would have walked into my office, plopped it down on my desk saying, REALLY? Turned and walked out... and shut the lights off as he left. Whew. Pathetic. What I really loved about the bench was returning it. They paid for the return.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="false" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>`,
      rating: 1,
      date: [Object],
      profile: [Object],
      vine_program: false,
      verified_purchase: true,
      review_country: "ca",
      is_global_review: true,
    },
  ],
  additional_details: [
    {
      name: "Small Business",
      value: "This product is from a small business brand. Support small.",
    },
  ],
  additional_details_flat:
    "Small Business: This product is from a small business brand. Support small.",
  buybox_winner: {
    maximum_order_quantity: { value: 14, hard_maximum: true },
    offer_id:
      "H/VAO4yMi5zGnPQFdqr9rlASmjyvt0tgOJEk3/uKOCOo8cpWORmlvJcZL5rNKkY1K6LPjsbPf696eyJZFoh/i9LaDnZpy5dykQhXB9S8xCZytrLqHPHtwlIpKzRDmGjw16eBkmEnH15YJmE9jIlDh55Cs1iFaNEUUJXHX4y4epgM5E0wsD/EMNB58oik2FMn",
    new_offers_count: 2,
    new_offers_from: {
      symbol: "$",
      value: 239.99,
      currency: "USD",
      raw: "$239.99",
    },
    is_prime: true,
    is_amazon_fresh: false,
    condition: { is_new: true },
    availability: {
      type: "in_stock",
      raw: "Only 14 left in stock - order soon.",
      dispatch_days: 1,
      stock_level: 14,
    },
    fulfillment: {
      type: "3p",
      standard_delivery: [Object],
      is_sold_by_amazon: false,
      is_fulfilled_by_amazon: false,
      is_fulfilled_by_third_party: true,
      is_sold_by_third_party: true,
      third_party_seller: [Object],
    },
    price: { symbol: "$", value: 239.99, currency: "USD", raw: "$239.99" },
    shipping: { raw: "FREE" },
  },
  more_buying_choices: [
    {
      price: [Object],
      seller_name: "Kunjek-VN",
      seller_link:
        "https://www.amazon.com/gp/aag/main?ie=UTF8&seller=A3OS0MP3NIHV1I&isAmazonFulfilled=0&asin=B087D88ZJM&ref_=dp_mbc_seller",
      position: 1,
    },
  ],
  specifications: [
    { name: "Material", value: "‎Wood" },
    { name: "Brand", value: "‎Olympia Tools" },
    {
      name: "Item Dimensions LxWxH",
      value: "‎55.51 x 20.87 x 5.12 inches",
    },
    { name: "Color", value: "‎Natural" },
    { name: "Item Weight", value: "‎0.01 Ounces" },
    { name: "Finish Type", value: "‎Varnish Finish" },
    { name: "Load Capacity", value: "‎330 pound" },
    { name: "Assembly Required", value: "‎Yes" },
    { name: "Manufacturer", value: "‎Olympia Tools" },
    { name: "Part Number", value: "‎88-128-917" },
    { name: "Item Weight", value: "‎0.01 ounces" },
    {
      name: "Product Dimensions",
      value: "‎55.51 x 20.87 x 5.12 inches",
    },
    { name: "Item model number", value: "‎88-128-917" },
    { name: "Style", value: "‎Acacia Wood" },
    { name: "Finish", value: "‎Varnish Finish" },
    { name: "Pattern", value: "‎Workbench" },
    { name: "Item Package Quantity", value: "‎1" },
    {
      name: "Included Components",
      value: "‎Workbench, instructions, workbench parts, hardware",
    },
    { name: "Batteries Included?", value: "‎No" },
    { name: "Batteries Required?", value: "‎No" },
    { name: "ASIN", value: "B087D88ZJM" },
    {
      name: "Customer Reviews",
      value: "4.2 out of 5 stars       892 ratings          4.2 out of 5 stars",
    },
    {
      name: "Best Sellers Rank",
      value: "#62,756 in Tools & Home Improvement",
    },
    { name: "Date First Available", value: "July 8, 2020" },
    { name: "Material", value: "Wood" },
    { name: "Brand", value: "Olympia Tools" },
    {
      name: "Item Dimensions LxWxH",
      value: "55.51 x 20.87 x 5.12 inches",
    },
    { name: "Color", value: "Natural" },
    { name: "Item Weight", value: "0.01 Ounces" },
  ],
  specifications_flat:
    "Item Weight: 0.01 Ounces. Color: Natural. Item Dimensions LxWxH: 55.51 x 20.87 x 5.12 inches. Brand: Olympia Tools. Material: Wood. Date First Available: July 8, 2020. Best Sellers Rank: #62,756 in Tools & Home Improvement. Customer Reviews: 4.2 out of 5 stars       892 ratings          4.2 out of 5 stars. ASIN: B087D88ZJM. Batteries Required?: ‎No. Batteries Included?: ‎No. Included Components: ‎Workbench, instructions, workbench parts, hardware. Item Package Quantity: ‎1. Pattern: ‎Workbench. Finish: ‎Varnish Finish. Style: ‎Acacia Wood. Item model number: ‎88-128-917. Product Dimensions: ‎55.51 x 20.87 x 5.12 inches. Item Weight: ‎0.01 ounces. Part Number: ‎88-128-917. Manufacturer: ‎Olympia Tools. Assembly Required: ‎Yes. Load Capacity: ‎330 pound. Finish Type: ‎Varnish Finish. Item Weight: ‎0.01 Ounces. Color: ‎Natural. Item Dimensions LxWxH: ‎55.51 x 20.87 x 5.12 inches. Brand: ‎Olympia Tools. Material: ‎Wood.",
  bestsellers_rank: [
    {
      category: "Tools & Home Improvement",
      rank: 62756,
      link: "https://www.amazon.com/gp/bestsellers/hi/ref=pd_zg_ts_hi",
    },
    {
      category: "Workbenches",
      rank: 45,
      link: "https://www.amazon.com/gp/bestsellers/hi/553602/ref=pd_zg_hrsr_hi",
    },
  ],
  color: "Natural",
  material: "Wood",
  manufacturer: "‎Olympia Tools",
  weight: "0.01 Ounces",
  first_available: { raw: "July 8, 2020", utc: "2020-07-08T00:00:00.000Z" },
  dimensions: "‎55.51 x 20.87 x 5.12 inches",
  model_number: "‎88-128-917",
  bestsellers_rank_flat:
    "Category: Tools & Home Improvement | Rank: 62756, Category: Workbenches | Rank: 45",
  whats_in_the_box: ["Workbench, instructions, workbench parts, hardware"],
};
